# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_location', models.TextField(verbose_name='File to download')),
                ('requester', models.IntegerField(verbose_name='userID of the account requesting to prevent cross account leakage')),
            ],
        ),
    ]
